# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_file_fill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='fill',
        ),
    ]
